apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.gui.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Values.gui.name }}
spec:
  type: {{ .Values.gui.service.type }}
  ports:
    - name: http-webserver
      port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: {{ .Values.gui.name }}
