name: gasket quadra
on:
  push:
    branches:
      - main
    paths:
      - "gasket/**"
      - ".github/workflows/gasket-quadra.yml"
      - "!gasket/images/xilinx-ffmpeg.Dockerfile"
  workflow_dispatch:
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set release env
        run: echo "RELEASE_DATE=$( date '+%F_%H:%M' )" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: pierrelefevreneti/quadra:gasket
          file: ./images/quadra.Dockerfile
          context: "{{defaultContext}}:gasket"
          build-args: |
            "RELEASE_BRANCH=quadra"
            "RELEASE_DATE=${{ env.RELEASE_DATE }}"
            "RELEASE_COMMIT=${{ github.sha }}"
