name: gasket lb
on:
  push:
    branches:
      - main
    paths:
      - "gasket-lb/**"
      - ".github/workflows/gasket-lb.yml"
  workflow_dispatch:
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set release env
        run: echo "RELEASE_DATE=$( date '+%F_%H:%M' )" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: pierrelefevreneti/gasket-lb
          file: ./Dockerfile
          context: "{{defaultContext}}:gasket-lb"
          build-args: |
            "RELEASE_BRANCH=ci"
            "RELEASE_DATE=${{ env.RELEASE_DATE }}"
            "RELEASE_COMMIT=${{ github.sha }}"
