name: xilinx ffmpeg
on:
  push:
    branches:
      - main
    paths:
      - "gasket/images/xilinx-ffmpeg.Dockerfile"
      - ".github/workflows/xilinx-ffmpeg.yml"
  workflow_dispatch:
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: pierrelefevreneti/xilinx-ffmpeg
          file: ./images/xilinx-ffmpeg.Dockerfile
          context: "{{defaultContext}}:gasket"
